remote_theme: just-the-docs/just-the-docs

title: Karel W. Dingeldey
description: A personal space
url: https://karel-dingeldey.de/
repository: criena/criena.github.io

plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"

# For copy button on code
enable_copy_code_button: true

# Show navigation error report
nav_error_report: true # default is false/nil.

liquid:
  error_mode: strict
  strict_filters: true

################################################################################

aux_links:
  "Criëna Network": https://criena.net/

nav_external_links:
  - title: Github
    url: https://github.com/criena/
  - title: LinkedIn
    url: https://www.linkedin.com/in/karel-dingeldey/

# Define Jekyll collections
collections:
  it:
    output: true
  recipes:
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    it:
      # Give the collection a name
      name: "IT Stuff"
      nav_fold: true  # note: this option is new in v0.4
    recipes:
      # Give the collection a name
      name: Recipes
      nav_fold: true  # note: this option is new in v0.4
